services:
  ai-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ai-backend
    container_name: ai-backend
    restart: unless-stopped

    ports:
      - "${BACKEND_PORT:-8000}:8000"

    env_file:
      - .env

    volumes:
      - ./backend/history.db:/app/history.db
